import { loadImage, loadImageAndTexture, loadImageAndTextureSpritesheet } from "./imageLoader";
import { loadSound } from "./soundLoader";

async function loadAssets(gl: WebGLRenderingContext) {
    console.log("[LOADING ASSETS...]");
    await Promise.all([
        // Tiles
        loadImageAndTexture(gl, "grass", "assets/images/tiles/grass.png"),
        loadImageAndTexture(gl, "water", "assets/images/tiles/water.png"),
        loadImageAndTexture(gl, "rocks", "assets/images/tiles/rocks.png"),
        loadImageAndTexture(gl, "path", "assets/images/tiles/path.png"),
        loadImageAndTexture(gl, "sand", "assets/images/tiles/sand.png"),
        loadImageAndTexture(gl, "planks", "assets/images/tiles/planks.png"),
        loadImageAndTexture(gl, "cursed_grass", "assets/images/tiles/cursed_grass.png"),
        loadImageAndTexture(gl, "cursed_path", "assets/images/tiles/cursed_path.png"),
        loadImageAndTexture(gl, "cursed_sand", "assets/images/tiles/cursed_sand.png"),
        loadImageAndTexture(gl, "cursed_planks", "assets/images/tiles/cursed_planks.png"),
        loadImageAndTextureSpritesheet(gl, "water", "assets/images/tiles/water_animation.png", 16, 16),
        loadImageAndTexture(gl, "school_tile", "assets/images/tiles/school_tile.png"),
        loadImageAndTexture(gl, "school_tile_black", "assets/images/tiles/school_tile_black.png"),
        loadImageAndTexture(gl, "school_wall", "assets/images/tiles/school_wall.png"),
        loadImageAndTexture(gl, "school_wall_side", "assets/images/tiles/school_wall_side.png"),
        loadImageAndTexture(gl, "school_wall_double_side", "assets/images/tiles/school_wall_double_side.png"),
        loadImageAndTexture(gl, "school_wall_inside_corner", "assets/images/tiles/school_wall_inside_corner.png"),
        loadImageAndTexture(gl, "school_wall_inside_corner_outside_corner", "assets/images/tiles/school_wall_inside_corner_outside_corner.png"),
        loadImageAndTexture(gl, "school_wall_u", "assets/images/tiles/school_wall_u.png"),
        loadImageAndTexture(gl, "school_wall_outside_corner", "assets/images/tiles/school_wall_outside_corner.png"),
        loadImageAndTexture(gl, "school_wall_side_outside_corner_top", "assets/images/tiles/school_wall_side_outside_corner_top.png"),
        loadImageAndTexture(gl, "school_wall_side_outside_corner_bottom", "assets/images/tiles/school_wall_side_outside_corner_bottom.png"),
        loadImageAndTexture(gl, "school_wall_side_double_outside_corner", "assets/images/tiles/school_wall_side_double_outside_corner.png"),
        loadImageAndTexture(gl, "gray_bricks", "assets/images/tiles/gray_bricks.png"),
        loadImageAndTexture(gl, "gym_floor", "assets/images/tiles/gym_floor.png"),
        
        // Entities
        loadImageAndTexture(gl, "character", "assets/images/character.png"),
        loadImageAndTexture(gl, "character_dead", "assets/images/character_dead.png"),
        loadImageAndTextureSpritesheet(gl, "character_idle", "assets/images/character_idle.png", 24, 42),
        loadImageAndTextureSpritesheet(gl, "character_run", "assets/images/character_run.png", 24, 42),
        loadImageAndTextureSpritesheet(gl, "character_idle_water", "assets/images/character_idle_water.png", 24, 42),

        loadImageAndTexture(gl, "minion", "assets/images/enemies/minion.png"),
        loadImageAndTexture(gl, "minion_water", "assets/images/enemies/minion_water.png"),
        loadImageAndTexture(gl, "minion_dead", "assets/images/enemies/minion_dead.png"),
        loadImageAndTexture(gl, "slime", "assets/images/enemies/slime.png"),
        loadImageAndTexture(gl, "slime_water", "assets/images/enemies/slime_water.png"),
        loadImageAndTexture(gl, "slime_dead", "assets/images/enemies/slime_dead.png"),
        loadImageAndTexture(gl, "revenant_eye", "assets/images/enemies/revenant_eye.png"),
        loadImageAndTexture(gl, "revenant_eye_attack", "assets/images/enemies/revenant_eye_attack.png"),
        loadImageAndTexture(gl, "revenant_eye_dead", "assets/images/enemies/revenant_eye_dead.png"),
        loadImageAndTexture(gl, "wraith", "assets/images/enemies/wraith.png"),
        loadImageAndTexture(gl, "wretched_skeleton", "assets/images/enemies/wretched_skeleton.png"),
        loadImageAndTexture(gl, "wretched_skeleton_water", "assets/images/enemies/wretched_skeleton_water.png"),
        loadImageAndTexture(gl, "wretched_skeleton_attack", "assets/images/enemies/wretched_skeleton_attack.png"),
        loadImageAndTexture(gl, "wretched_skeleton_dead", "assets/images/enemies/wretched_skeleton_dead.png"),
        loadImageAndTexture(gl, "evil_bunny", "assets/images/enemies/evil_bunny.png"),
        loadImageAndTexture(gl, "evil_bunny_attack", "assets/images/enemies/evil_bunny_attack.png"),
        loadImageAndTexture(gl, "evil_bunny_dead", "assets/images/enemies/evil_bunny_dead.png"),
        loadImageAndTexture(gl, "red_slime", "assets/images/enemies/red_slime.png"),
        loadImageAndTexture(gl, "ground_worm", "assets/images/enemies/ground_worm.png"),
        loadImageAndTexture(gl, "ground_worm_dead", "assets/images/enemies/ground_worm_dead.png"),
        loadImageAndTexture(gl, "corrupted_deer", "assets/images/enemies/corrupted_deer.png"),
        loadImageAndTexture(gl, "corrupted_deer_dead", "assets/images/enemies/corrupted_deer_dead.png"),
        loadImageAndTexture(gl, "corrupted_deer_attack", "assets/images/enemies/corrupted_deer_attack.png"),
        loadImageAndTexture(gl, "fungal_husk", "assets/images/enemies/fungal_husk.png"),
        loadImageAndTexture(gl, "fungal_husk_dead", "assets/images/enemies/fungal_husk_dead.png"),
        loadImageAndTexture(gl, "fungal_husk_attack", "assets/images/enemies/fungal_husk_attack.png"),
        loadImageAndTexture(gl, "fungal_spirit", "assets/images/enemies/fungal_spirit.png"),

        loadImageAndTexture(gl, "portal_small", "assets/images/portal_small.png"),
        loadImageAndTexture(gl, "portal_medium", "assets/images/portal_medium.png"),
        loadImageAndTexture(gl, "essence_orb_small", "assets/images/essence_orb_small.png"),

        // Props
        loadImageAndTexture(gl, "tree", "assets/images/props/tree.png"),
        loadImageAndTexture(gl, "evergreen_tree", "assets/images/props/evergreen_tree.png"),
        loadImageAndTexture(gl, "stone_1", "assets/images/props/stone_1.png"),
        loadImageAndTexture(gl, "white_stone_1", "assets/images/props/white_stone_1.png"),
        loadImageAndTexture(gl, "red_wildflower", "assets/images/props/red_wildflower.png"),
        loadImageAndTexture(gl, "yellow_wildflower", "assets/images/props/yellow_wildflower.png"),
        loadImageAndTexture(gl, "bush", "assets/images/props/bush.png"),
        loadImageAndTexture(gl, "tall_grass", "assets/images/props/tall_grass.png"),
        loadImageAndTexture(gl, "unlit_campfire", "assets/images/props/unlit_campfire.png"),
        loadImageAndTexture(gl, "tree_stump", "assets/images/props/tree_stump.png"),
        loadImageAndTexture(gl, "mossy_fallen_tree", "assets/images/props/mossy_fallen_tree.png"),
        loadImageAndTexture(gl, "toilet", "assets/images/props/toilet.png"),
        loadImageAndTexture(gl, "sink", "assets/images/props/sink.png"),
        loadImageAndTexture(gl, "chalk_board", "assets/images/props/chalk_board.png"),
        loadImageAndTexture(gl, "school_desk", "assets/images/props/school_desk.png"),
        loadImageAndTexture(gl, "basketball", "assets/images/props/basketball.png"),
        loadImageAndTexture(gl, "lunch_table", "assets/images/props/lunch_table.png"),
        
        // Projectiles
        loadImageAndTexture(gl, "arrow", "assets/images/projectiles/arrow.png"),
        loadImageAndTexture(gl, "poison_arrow", "assets/images/projectiles/poison_arrow.png"),
        loadImageAndTexture(gl, "ricochet_arrow", "assets/images/projectiles/ricochet_arrow.png"),
        loadImageAndTexture(gl, "tear_drop", "assets/images/projectiles/tear_drop.png"),
        loadImageAndTexture(gl, "wraith_attack", "assets/images/projectiles/wraith_attack.png"),
        loadImageAndTexture(gl, "rock", "assets/images/projectiles/rock.png"),
        loadImageAndTexture(gl, "crystal_shard", "assets/images/projectiles/crystal_shard.png"),
        loadImageAndTexture(gl, "flower_power_petal", "assets/images/projectiles/flower_petal.png"),
        loadImageAndTexture(gl, "playing_card", "assets/images/projectiles/playing_card.png"),
        loadImageAndTexture(gl, "dove", "assets/images/projectiles/dove.png"),
        loadImageAndTexture(gl, "rubber_chicken", "assets/images/projectiles/rubber_chicken.png"),
        loadImageAndTexture(gl, "water_drop", "assets/images/projectiles/water_drop.png"),


        // Item icons
        loadImageAndTexture(gl, "broad_sword_icon", "assets/images/items/broad_sword_icon.png"),
        loadImageAndTexture(gl, "shuriken", "assets/images/items/shuriken.png"),
        loadImageAndTexture(gl, "bow", "assets/images/items/bow.png"),
        loadImageAndTexture(gl, "arrow_icon", "assets/images/items/arrow_icon.png"),
        loadImageAndTexture(gl, "healing_vial", "assets/images/items/healing_vial.png"),
        loadImageAndTexture(gl, "battle_hammer",  "assets/images/items/battle_hammer.png"),
        loadImageAndTexture(gl, "crystal_bomb", "assets/images/items/crystal_bomb.png"),
        loadImageAndTexture(gl, "daggers", "assets/images/items/daggers.png"),
        loadImageAndTexture(gl, "essence_dripped_dagger", "assets/images/items/essence_dripped_dagger.png"),
        loadImageAndTexture(gl, "essence_vial", "assets/images/items/essence_vial.png"),
        loadImageAndTexture(gl, "flame_upgrade", "assets/images/items/flame_upgrade.png"),
        loadImageAndTexture(gl, "heart_crystal", "assets/images/items/heart_crystal.png"),
        loadImageAndTexture(gl, "heart", "assets/images/items/heart.png"),
        loadImageAndTexture(gl, "poison_arrow_icon", "assets/images/items/poison_arrow.png"),
        loadImageAndTexture(gl, "flame_arrow_icon", "assets/images/items/flame_arrow.png"),
        loadImageAndTexture(gl, "poison_upgrade", "assets/images/items/poison_upgrade.png"),
        loadImageAndTexture(gl, "slingshot", "assets/images/items/slingshot.png"),
        loadImageAndTexture(gl, "strength_upgrade", "assets/images/items/strength_upgrade.png"),
        loadImageAndTexture(gl, "stun_fiddle", "assets/images/items/stun_fiddle.png"),
        loadImageAndTexture(gl, "teleportation_rune", "assets/images/items/teleportation_rune.png"),
        loadImageAndTexture(gl, "root_snare", "assets/images/items/root_snare.png"),
        loadImageAndTexture(gl, "basic_shield", "assets/images/items/basic_shield.png"),
        loadImageAndTexture(gl, "quick_bow", "assets/images/items/quick_bow.png"),
        loadImageAndTexture(gl, "dice", "assets/images/items/dice.png"),
        loadImageAndTexture(gl, "ghost_arrows", "assets/images/items/ghost_arrows.png"),
        loadImageAndTexture(gl, "ghost_bow", "assets/images/items/ghost_bow.png"),
        loadImageAndTexture(gl, "strong_sword", "assets/images/items/strong_sword.png"),
        loadImageAndTexture(gl, "poison_strong_sword", "assets/images/items/poison_strong_sword.png"),
        loadImageAndTexture(gl, "poison_broad_sword", "assets/images/items/poison_broad_sword.png"),
        loadImageAndTexture(gl, "boomerang", "assets/images/items/boomerang.png"),
        loadImageAndTexture(gl, "ricochet_boomerang", "assets/images/items/ricochet_boomerang.png"),
        loadImageAndTexture(gl, "ricochet_upgrade", "assets/images/items/ricochet_upgrade.png"),
        loadImageAndTexture(gl, "ricochet_bow", "assets/images/items/ricochet_bow.png"),
        loadImageAndTexture(gl, "sprocket_upgrade", "assets/images/items/sprocket_upgrade.png"),
        loadImageAndTexture(gl, "reinforced_slingshot", "assets/images/items/reinforced_slingshot.png"),
        loadImageAndTexture(gl, "machine_gun_slingshot", "assets/images/items/machine_gun_slingshot.png"),
        loadImageAndTexture(gl, "invincibility_bubble", "assets/images/items/invincibility_bubble.png"),
        loadImageAndTexture(gl, "poison_battle_hammer", "assets/images/items/poison_battle_hammer.png"),
        loadImageAndTexture(gl, "quick_battle_hammer", "assets/images/items/quick_battle_hammer.png"),
        loadImageAndTexture(gl, "quick_broad_sword", "assets/images/items/quick_broad_sword.png"),
        loadImageAndTexture(gl, "quick_hand_upgrade", "assets/images/items/quick_hand_upgrade.png"),
        loadImageAndTexture(gl, "flower_power", "assets/images/items/flower_power.png"),
        loadImageAndTexture(gl, "light_boots", "assets/images/items/light_boots.png"),
        loadImageAndTexture(gl, "essence_magnet", "assets/images/items/essence_magnet.png"),
        loadImageAndTexture(gl, "power_bow", "assets/images/items/power_bow.png"),
        loadImageAndTexture(gl, "water_gun", "assets/images/items/water_gun.png"),
        loadImageAndTexture(gl, "pressure_washer", "assets/images/items/pressure_washer.png"),
        loadImageAndTexture(gl, "water_bottle_0", "assets/images/items/water_bottle_0.png"),
        loadImageAndTexture(gl, "water_bottle_1", "assets/images/items/water_bottle_1.png"),
        loadImageAndTexture(gl, "water_bottle_2", "assets/images/items/water_bottle_2.png"),
        loadImageAndTexture(gl, "water_bottle_3", "assets/images/items/water_bottle_3.png"),
        loadImageAndTexture(gl, "water_bottle_4", "assets/images/items/water_bottle_4.png"),
        loadImageAndTexture(gl, "water_bottle_5", "assets/images/items/water_bottle_5.png"),
        loadImageAndTexture(gl, "water_bottle_6", "assets/images/items/water_bottle_6.png"),
        loadImageAndTexture(gl, "composition_notebook", "assets/images/items/composition_notebook.png"),
        loadImageAndTexture(gl, "fire_alarm", "assets/images/items/fire_alarm.png"),
        loadImageAndTexture(gl, "lunch_box", "assets/images/items/lunch_box.png"),
        loadImageAndTexture(gl, "mechanical_pencil", "assets/images/items/mechanical_pencil.png"),
        loadImageAndTexture(gl, "milk_carton", "assets/images/items/milk_carton.png"),
        loadImageAndTexture(gl, "mystery_pudding", "assets/images/items/mystery_pudding.png"),
        loadImageAndTexture(gl, "pencil", "assets/images/items/pencil.png"),
        loadImageAndTexture(gl, "scissors", "assets/images/items/scissors.png"),
        loadImageAndTexture(gl, "soda_grenade", "assets/images/items/soda_grenade.png"),
        loadImageAndTexture(gl, "spray_paint", "assets/images/items/spray_paint.png"),
        loadImageAndTexture(gl, "textbook", "assets/images/items/textbook.png"),
        loadImageAndTexture(gl, "volcano", "assets/images/items/volcano.png"),
        
        // Particle sprites
        loadImageAndTexture(gl, "portal_particle", "assets/images/particles/portal_particle.png"),
        loadImageAndTexture(gl, "sword_spark", "assets/images/particles/sword_spark.png"),
        loadImageAndTexture(gl, "slime_particle", "assets/images/particles/slime_particle.png"),
        loadImageAndTexture(gl, "poison_particle", "assets/images/particles/poison.png"),
        loadImageAndTexture(gl, "flame_particle", "assets/images/particles/flame.png"),
        loadImageAndTexture(gl, "stun_particle", "assets/images/particles/stun.png"),
        loadImageAndTexture(gl, "cracks_particle", "assets/images/particles/cracks.png"),
        loadImageAndTexture(gl, "husk_particle", "assets/images/particles/husk.png"),
    
        loadImageAndTextureSpritesheet(gl, "pixel_font", "assets/images/font_small.png", 5, 5, ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "1", "2", "3", "4", "5", "6", "7", "8", "9", "0"]),

        // UI
        loadImage("inventory_slot", "assets/images/ui/inventory_slot.png"),
        loadImage("selected_slot", "assets/images/ui/selected_slot.png"),
        loadImage("buff_slot", "assets/images/ui/buff_slot.png"),
        loadImage("consumable_slot", "assets/images/ui/consumable_slot.png"),
        loadImage("selected_consumable_slot", "assets/images/ui/selected_consumable_slot.png"),
        loadImage("quiver_slot", "assets/images/ui/quiver_slot.png"),
        loadImage("utility_slot", "assets/images/ui/utility_slot.png"),
        loadImage("selected_utility_slot", "assets/images/ui/selected_utility_slot.png"),
        loadImage("weapon_slot", "assets/images/ui/weapon_slot.png"),
        loadImage("selected_weapon_slot", "assets/images/ui/selected_weapon_slot.png"),
        loadImage("upgrade_slot", "assets/images/ui/upgrade_slot.png"),
        loadImage("trash_slot", "assets/images/ui/trash_slot.png"),
        
        loadImage("essence_jar_small_0", "assets/images/ui/essence_jar_small_0.png"),
        loadImage("essence_jar_small_1", "assets/images/ui/essence_jar_small_1.png"),
        loadImage("essence_jar_small_2", "assets/images/ui/essence_jar_small_2.png"),
        loadImage("essence_jar_small_3", "assets/images/ui/essence_jar_small_3.png"),
        loadImage("essence_jar_small_4", "assets/images/ui/essence_jar_small_4.png"),
        loadImage("essence_jar_small_5", "assets/images/ui/essence_jar_small_5.png"),
        loadImage("essence_jar_small_6", "assets/images/ui/essence_jar_small_6.png"),
        loadImage("essence_jar_small_7", "assets/images/ui/essence_jar_small_7.png"),
        loadImage("essence_jar_small_8", "assets/images/ui/essence_jar_small_8.png"),
        
        loadImage("attack_cooldown_0", "assets/images/ui/attack_reload_0.png"),
        loadImage("attack_cooldown_1", "assets/images/ui/attack_reload_1.png"),
        loadImage("attack_cooldown_2", "assets/images/ui/attack_reload_2.png"),
        loadImage("attack_cooldown_3", "assets/images/ui/attack_reload_3.png"),
        loadImage("attack_cooldown_4", "assets/images/ui/attack_reload_4.png"),
        loadImage("attack_cooldown_5", "assets/images/ui/attack_reload_5.png"),
        loadImage("attack_cooldown_6", "assets/images/ui/attack_reload_6.png"),
        loadImage("attack_cooldown_7", "assets/images/ui/attack_reload_7.png"),
        loadImage("attack_cooldown_8", "assets/images/ui/attack_reload_8.png"),
        loadImage("attack_cooldown_9", "assets/images/ui/attack_reload_9.png"),

        loadImage("attack_charge_0", "assets/images/ui/attack_charge_0.png"),
        loadImage("attack_charge_1", "assets/images/ui/attack_charge_1.png"),
        loadImage("attack_charge_2", "assets/images/ui/attack_charge_2.png"),
        loadImage("attack_charge_3", "assets/images/ui/attack_charge_3.png"),
        loadImage("attack_charge_4", "assets/images/ui/attack_charge_4.png"),
        loadImage("attack_charge_5", "assets/images/ui/attack_charge_5.png"),
        loadImage("attack_charge_6", "assets/images/ui/attack_charge_6.png"),
        loadImage("attack_charge_7", "assets/images/ui/attack_charge_7.png"),
        loadImage("attack_charge_8", "assets/images/ui/attack_charge_8.png"),
        loadImage("attack_charge_9", "assets/images/ui/attack_charge_9.png"),

        loadImage("cooldown_0", "assets/images/ui/cooldown_0.png"),
        loadImage("cooldown_1", "assets/images/ui/cooldown_1.png"),
        loadImage("cooldown_2", "assets/images/ui/cooldown_2.png"),
        loadImage("cooldown_3", "assets/images/ui/cooldown_3.png"),
        loadImage("cooldown_4", "assets/images/ui/cooldown_4.png"),
        loadImage("cooldown_5", "assets/images/ui/cooldown_5.png"),
        loadImage("cooldown_6", "assets/images/ui/cooldown_6.png"),
        loadImage("cooldown_7", "assets/images/ui/cooldown_7.png"),
        loadImage("cooldown_8", "assets/images/ui/cooldown_8.png"),
        loadImage("cooldown_9", "assets/images/ui/cooldown_9.png"),
        loadImage("cooldown_10", "assets/images/ui/cooldown_10.png"),
        loadImage("cooldown_11", "assets/images/ui/cooldown_11.png"),
        loadImage("cooldown_12", "assets/images/ui/cooldown_12.png"),
        loadImage("cooldown_13", "assets/images/ui/cooldown_13.png"),
        loadImage("cooldown_14", "assets/images/ui/cooldown_14.png"),
        loadImage("cooldown_15", "assets/images/ui/cooldown_15.png"),
        
        loadImage("status_effect_slot", "assets/images/ui/status_effect_slot.png"),
        
        loadImage("invincibility_effect_icon", "assets/images/status_effects/invincibility_icon.png"),
        loadImage("poison_effect_icon", "assets/images/status_effects/poison_icon.png"),
        loadImage("flame_effect_icon", "assets/images/status_effects/flame_icon.png"),

        // Misc.
        loadImageAndTexture(gl, "square",  "assets/images/square.png"),
        loadImageAndTexture(gl, "undefined", "assets/images/undefined.png"),
        loadImageAndTexture(gl, "right_arrow", "assets/images/right_arrow.png"),
        loadImageAndTexture(gl, "antenna", "assets/images/antenna.png"),

        // -- SOUNDS --
        loadSound("item_pickup", "assets/sounds/item_pickup.wav", 5),
        loadSound("essence_pickup", "assets/sounds/essence_pickup.wav", 1),
        loadSound("peach_damage", "assets/sounds/peach_damage.wav", 1),
        loadSound("peach_die", "assets/sounds/peach_die.wav", 1),
        loadSound("hitmarker", "assets/sounds/hitmarker.mp3", 1),
        loadSound("portal_break", "assets/sounds/portal_break.mp3", 1),
    ]);
    console.log("[FINISHED LOADING ASSETS...]");
}

export { loadAssets };
